### ISSUE TITLE
Merge commit dialog stucks if there are non-parseable return messages

### ISSUE THREAD

**Issue by ammsalme** [NatLibFi/marc-merge-ui#100]
Caused by:
- anything melinda-api-client can't parse (code -1)
- message 25000, "Input record exceeds 25000 bytes, checking and updating may take longer than usual."

**Comment by aatuny** [comment]
This issue is pretty relevant, because it causes errors. The lack of feedback invokes users to try again and that makes unnecessary records to the database.
